# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ad_sheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='performance.Student'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='linked',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='performance.Student'),
        ),
    ]
