# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_auto_20161205_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='ad_sheet',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
