# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_auto_20161205_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='linked',
            new_name='student',
        ),
    ]
