# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_auto_20161205_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='first',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='second',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='third',
        ),
        migrations.AddField(
            model_name='subject',
            name='first_subject',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='second_subject',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='third_subject',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
