# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='first_subject',
            new_name='subject_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='second_subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='third_subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='full_mark',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_mark',
            field=models.IntegerField(default=45),
        ),
    ]
