# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_auto_20161205_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='mark_obtained',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
