# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_subject_mark_obtained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='full_mark',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='mark_obtained',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='pass_mark',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_name',
        ),
    ]
