# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0010_auto_20161207_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(choices=[('', ''), ('math', 'Math'), ('science', 'Science'), ('geography', 'Geography'), ('spanish', 'Spanish'), ('french', 'French'), ('english', 'English'), ('accounts', 'Accounts')], default='', max_length=120),
        ),
    ]
